### ISSUE TITLE
Styled-Components missing

### ISSUE THREAD

**Issue by saisandeepvaddi** [aantipov/moiva-catalog#12] opened 2020-12-22 18:58 UTC
Hi,

First of all amazing tool. Great Job.

As you might already know, styled-components is one of the most used libraries and it is missing from the search. Of course, I can add it to the address bar URL and compare but I feel it would be great if it shows up in the search as the libs with far fewer downloads show up in the search.

I feel styled-components is essential when you go to compare any CSS-in-JS libraries.

Could you please consider adding it?

Thanks

**Comment by aantipov** [comment] 2020-12-23 11:43
Hi @saisandeepvaddi 
Thanks for reporting. I know about the issue, it will be fixed soon once I migrate from npms.io to npmjs api.

**Comment by aantipov** [comment] 2020-12-23 15:33
The issue is fixed. Should work fine now

**Closed as completed** 2020-12-23 15:33 UTC

**Comment by saisandeepvaddi** [comment] 2020-12-23 16:28
Awesome :) 💯

Have a great day 👍🏼
